/*
Deployment script for StateExclusionsDatabase3

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "StateExclusionsDatabase3"
:setvar DefaultFilePrefix "StateExclusionsDatabase3"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[StateExcl_Exclusion]...';


GO
CREATE TABLE [dbo].[StateExcl_Exclusion] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [ExclusionName]        NVARCHAR (MAX) NOT NULL,
    [ExclusionDescription] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_StateExcl_Exclusion] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[StateExcl_ExclusionDate]...';


GO
CREATE TABLE [dbo].[StateExcl_ExclusionDate] (
    [Id]                    INT      IDENTITY (1, 1) NOT NULL,
    [ExclusionDate]         DATETIME NOT NULL,
    [StateExcl_ExclusionId] INT      NOT NULL,
    CONSTRAINT [PK_StateExcl_ExclusionDate] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[StateExcl_ExclusionDate].[IX_FK_StateExcl_ExclusionStateExcl_ExclusionDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_FK_StateExcl_ExclusionStateExcl_ExclusionDate]
    ON [dbo].[StateExcl_ExclusionDate]([StateExcl_ExclusionId] ASC);


GO
PRINT N'Creating [dbo].[StateExcl_State]...';


GO
CREATE TABLE [dbo].[StateExcl_State] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [StateName]         NVARCHAR (MAX) NOT NULL,
    [StateAbbreviation] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_StateExcl_State] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[StateExcl_StateExclusion]...';


GO
CREATE TABLE [dbo].[StateExcl_StateExclusion] (
    [Id]                    INT IDENTITY (1, 1) NOT NULL,
    [StateExcl_StateId]     INT NOT NULL,
    [StateExcl_ExclusionId] INT NOT NULL,
    CONSTRAINT [PK_StateExcl_StateExclusion] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[StateExcl_StateExclusion].[IX_FK_StateExcl_StateStateExcl_StateExclusion]...';


GO
CREATE NONCLUSTERED INDEX [IX_FK_StateExcl_StateStateExcl_StateExclusion]
    ON [dbo].[StateExcl_StateExclusion]([StateExcl_StateId] ASC);


GO
PRINT N'Creating [dbo].[StateExcl_StateExclusion].[IX_FK_StateExcl_ExclusionStateExcl_StateExclusion]...';


GO
CREATE NONCLUSTERED INDEX [IX_FK_StateExcl_ExclusionStateExcl_StateExclusion]
    ON [dbo].[StateExcl_StateExclusion]([StateExcl_ExclusionId] ASC);


GO
PRINT N'Creating [dbo].[FK_StateExcl_ExclusionStateExcl_ExclusionDate]...';


GO
ALTER TABLE [dbo].[StateExcl_ExclusionDate] WITH NOCHECK
    ADD CONSTRAINT [FK_StateExcl_ExclusionStateExcl_ExclusionDate] FOREIGN KEY ([StateExcl_ExclusionId]) REFERENCES [dbo].[StateExcl_Exclusion] ([Id]);


GO
PRINT N'Creating [dbo].[FK_StateExcl_StateStateExcl_StateExclusion]...';


GO
ALTER TABLE [dbo].[StateExcl_StateExclusion] WITH NOCHECK
    ADD CONSTRAINT [FK_StateExcl_StateStateExcl_StateExclusion] FOREIGN KEY ([StateExcl_StateId]) REFERENCES [dbo].[StateExcl_State] ([Id]);


GO
PRINT N'Creating [dbo].[FK_StateExcl_ExclusionStateExcl_StateExclusion]...';


GO
ALTER TABLE [dbo].[StateExcl_StateExclusion] WITH NOCHECK
    ADD CONSTRAINT [FK_StateExcl_ExclusionStateExcl_StateExclusion] FOREIGN KEY ([StateExcl_ExclusionId]) REFERENCES [dbo].[StateExcl_Exclusion] ([Id]);


GO
PRINT N'Creating [dbo].[StateExcl_StateExclusionView]...';


GO
CREATE VIEW dbo.StateExcl_StateExclusionView
AS
SELECT        dbo.StateExcl_State.StateName, dbo.StateExcl_State.StateAbbreviation, dbo.StateExcl_StateExclusion.Id AS StateExclusionId, dbo.StateExcl_Exclusion.ExclusionName, dbo.StateExcl_Exclusion.ExclusionDescription, 
                         dbo.StateExcl_State.Id AS StateId, dbo.StateExcl_Exclusion.Id AS ExclusionId, dbo.StateExcl_ExclusionDate.Id AS ExclusionDateId, dbo.StateExcl_ExclusionDate.ExclusionDate
FROM            dbo.StateExcl_ExclusionDate INNER JOIN
                         dbo.StateExcl_Exclusion ON dbo.StateExcl_ExclusionDate.StateExcl_ExclusionId = dbo.StateExcl_Exclusion.Id INNER JOIN
                         dbo.StateExcl_StateExclusion ON dbo.StateExcl_Exclusion.Id = dbo.StateExcl_StateExclusion.StateExcl_ExclusionId INNER JOIN
                         dbo.StateExcl_State ON dbo.StateExcl_StateExclusion.StateExcl_StateId = dbo.StateExcl_State.Id
GO
PRINT N'Creating [dbo].[StateExclusionView]...';


GO
CREATE VIEW dbo.StateExclusionView
AS
SELECT        dbo.StateExcl_State.StateName, dbo.StateExcl_State.StateAbbreviation, dbo.StateExcl_StateExclusion.Id AS StateExclusionId, dbo.StateExcl_Exclusion.ExclusionName, dbo.StateExcl_Exclusion.ExclusionDescription, 
                         dbo.StateExcl_State.Id AS StateId, dbo.StateExcl_Exclusion.Id AS ExclusionId, dbo.StateExcl_ExclusionDate.Id AS ExclusionDateId, dbo.StateExcl_ExclusionDate.ExclusionDate
FROM            dbo.StateExcl_ExclusionDate INNER JOIN
                         dbo.StateExcl_Exclusion ON dbo.StateExcl_ExclusionDate.StateExcl_ExclusionId = dbo.StateExcl_Exclusion.Id INNER JOIN
                         dbo.StateExcl_StateExclusion ON dbo.StateExcl_Exclusion.Id = dbo.StateExcl_StateExclusion.StateExcl_ExclusionId INNER JOIN
                         dbo.StateExcl_State ON dbo.StateExcl_StateExclusion.StateExcl_StateId = dbo.StateExcl_State.Id
GO
PRINT N'Creating [dbo].[StateExcl_StateExclusionView].[MS_DiagramPane1]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "StateExcl_ExclusionDate"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 119
               Right = 239
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "StateExcl_Exclusion"
            Begin Extent = 
               Top = 6
               Left = 277
               Bottom = 119
               Right = 476
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "StateExcl_StateExclusion"
            Begin Extent = 
               Top = 6
               Left = 514
               Bottom = 119
               Right = 715
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "StateExcl_State"
            Begin Extent = 
               Top = 6
               Left = 753
               Bottom = 119
               Right = 936
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'StateExcl_StateExclusionView';


GO
PRINT N'Creating [dbo].[StateExcl_StateExclusionView].[MS_DiagramPaneCount]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'StateExcl_StateExclusionView';


GO
PRINT N'Creating [dbo].[StateExclusionView].[MS_DiagramPane1]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[30] 4[31] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "StateExcl_ExclusionDate"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 119
               Right = 239
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "StateExcl_Exclusion"
            Begin Extent = 
               Top = 6
               Left = 277
               Bottom = 119
               Right = 476
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "StateExcl_StateExclusion"
            Begin Extent = 
               Top = 6
               Left = 514
               Bottom = 119
               Right = 715
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "StateExcl_State"
            Begin Extent = 
               Top = 6
               Left = 753
               Bottom = 119
               Right = 936
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 3405
         Alias = 2595
         Table = 3480
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
  ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'StateExclusionView';


GO
PRINT N'Creating [dbo].[StateExclusionView].[MS_DiagramPane2]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane2', @value = N'       Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'StateExclusionView';


GO
PRINT N'Creating [dbo].[StateExclusionView].[MS_DiagramPaneCount]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 2, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'StateExclusionView';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[StateExcl_ExclusionDate] WITH CHECK CHECK CONSTRAINT [FK_StateExcl_ExclusionStateExcl_ExclusionDate];

ALTER TABLE [dbo].[StateExcl_StateExclusion] WITH CHECK CHECK CONSTRAINT [FK_StateExcl_StateStateExcl_StateExclusion];

ALTER TABLE [dbo].[StateExcl_StateExclusion] WITH CHECK CHECK CONSTRAINT [FK_StateExcl_ExclusionStateExcl_StateExclusion];


GO
PRINT N'Update complete.';


GO
